apiVersion: apps/v1
kind: DatadogMonitor
metadata:
  name: imagebackoff
spec:
  query: max(last_10m):default_zero(max:kubernetes_state.container.status_report.count.waiting{reason:imagebackoff} by {kube_cluster_name,kube_namespace,pod_name}) >= 1
  type: "query alert"
  name: "iamgebackoffascode"
  message: pod {{pod_name.name}} is in ImageBackOff on {{kube_namespace.name}} @world666.best@gmail.com
  tags:
    - "integration:kubernetes"
  priority: null
  options:
    evaluationDelay: 300
    includeTags: true
    locked: false
    newGroupDelay: 300
    notifyNoData: false
    noDataTimeframe: 30
    renotifyInterval: 0
    thresholds:
      critical: "1"
      warning: "0.28"